MyJournal/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyJournal.Controllers
{
    public class AlbumsController : Controller
    {
        // GET: Album
        [Authorize]
        public ActionResult Index()
        {
                return base.View();
        }

        [Authorize]
        public ViewResult Detail(string albumName)
        {
            return View((object)albumName);
        }

        public ViewResult ResourceUploader(string albumName)
        {
            return View((object) albumName);
        }
    }
}

MyJournal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="app" id="overrides">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Journal</title>
    <link href='https://fonts.googleapis.com/css?family=Jura:500,600' rel='stylesheet' type='text/css'>

    @Styles.Render("~/Content/css")
    <link rel="dx-theme" data-theme="generic.light" href="~/css/dx.light.css" data-active="true" />
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/md5")
    @Scripts.Render("~/bundles/fileSaver")
    @Scripts.Render("~/bundles/devExpress")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Journal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Your Albums", "Index", "Albums")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div data-ng-view=""></div>
        @*@RenderBody()*@
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Journal</p>
        </footer>
    </div>

@*@Scripts.Render("~/bundles/bootstrap")*@
@RenderSection("scripts", required: false)

<script type="text/javascript" src="~/app/services/authService.js"></script>
<script type="text/javascript" src="~/app/services/authInerceptorService.js"></script>
<script type="text/javascript" src="~/app/services/albumprovider.js"></script>
<script type="text/javascript" src="~/app/app.js"></script>
<script type="text/javascript" src="~/app/Controllers/albumuploadcontroller.js"></script>
<script type="text/javascript" src="~/app/Controllers/albumlistcontroller.js"></script>
<script type="text/javascript" src="~/app/Controllers/loginController.js"></script>
<script type="text/javascript" src="~/app/Controllers/albumviewcontroller.js"></script>
</body>
</html>